baseURL = 'https://louisdutton.dev/'
languageCode = 'en-gb'
title = 'Louis Dutton'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'base16-default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi there'
homeIntroContent = """
Full-stack software engineer based in Cornwall, UK.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/louisdutton"

# Main menu pages
[[params.menu]]
name = "Home"
url = "/"

[[params.menu]]
name = "Posts"
url = "/posts"

# [[params.menu]]
# name = "Resume"
# url = "/resume"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'
